### ISSUE TITLE
How can i build it for android?

### ISSUE THREAD

**Issue by xiongziliang** [namjaejeon/cifsd-tools#16]
I want use this project in android as cifs server,could you tell me how can i build it for andorid ? Thank you very much!

**Comment by namjaejeon** [comment]
Hi,
Have you read CIFSD_User_Guide_v1.0.pdf(in https://github.com/namjaejeon/Documents) ?
If you didn't read it, let's discuss again if you have a question after reading and trying to build as guide.

Thanks.

**Comment by namjaejeon** [comment]
Could you specifically explain what you face issues when appying cifsd to android ?
user guide explain how to build cifsd in linux environment. and android is also based on linux.

**Comment by xiongziliang** [comment]
I want just use this project as one part of my application by JNI interface on android , i have read the PDF document not very carefully just now, it seems that , cifs service module  can just run as one part of linux kernel , is it right? 

I built your another project(named:"cifsd") last night through the way of JNI  on android , but i failed.
I do not know how can i add cifs service ability to my application，could you tell me whether this project meet my needs ?

Thank you very much!

**Comment by namjaejeon** [comment]
Okay, I got it :)
You are confusing cifsd kernel module and cifsd in cifsd-tools.
to help your understanding, You can read this wiki page => https://en.wikipedia.org/wiki/CIFSD

cifsd consist of userspace daemon cifsd and kernel daemon kcifsd of linux kernel module, which mean cifsd which you are saying another project(named:cifsd) is not separated project.
cifsd and cifsd-tools are one project. you should make both cifsd kernel module and cifsd in cifsd-tools to execute cifsd. for this one, you need to build your linux kernel source of andorid target after adding cifsd as user guide.

And the build failure you got means gcc build failed ? or build failutre with your application together ?
cifsd is stand-alone. if you got build failure of cifsd-tools using gcc, let me know build failure log.

Thanks~

**Comment by namjaejeon** [comment]
Hey,
I didn't think it is not issue.
Could I close this issue  ? or you are checking more ?

Thanks :)

**Comment by xiongziliang** [comment]
Ok thank you very much!
