### ISSUE TITLE
Segmentation fault if cifsdpwd.db does not exists.

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd-tools#62]
Getting a segfault and hanging process, if i try to start cifsd, with no database file. This should be allowed if i just want to run via guest.
```
guest ok = yes
map to guest = Bad User
```

```
cifsd -n
[cifsd-worker/13707]: ERROR: Can't open `/etc/cifs/cifsdpwd.db': No such file or directory
[cifsd-worker/13707]: ERROR: Unable to parse user database
[cifsd-worker/13707]: ERROR: Failed to parse configuration files
[cifsd-worker/13707]: ERROR: Child received signal: 11 (Segmentation fault)
```

**Comment by namjaejeon** [comment]
Got it, Will fix it!
Thanks for your report!

**Comment by sergey-senozhatsky** [comment]
FIXED

**Comment by namjaejeon** [comment]
pushed the patches from Sergey to master branch now.

**Comment by Andy2244** [comment]
Ok seems the segfault is fixed, yet i still need to create a dummy database user even for a guest only setup.

```
cifsd -n
[cifsd-worker/14326]: ERROR: Can't open `/etc/cifs/cifsdpwd.db': No such file or directory
[cifsd-worker/14326]: ERROR: Unable to parse user database
[cifsd-worker/14326]: ERROR: Failed to parse configuration files
[cifsd-manager/14325]: ERROR: WARNING: child process exited abnormally: 14326
```

**Comment by sergey-senozhatsky** [comment]
> yet i still need to create a dummy database user even for a guest only setup.

Will take a look.

-ss

**Comment by sergey-senozhatsky** [comment]
@Andy2244 

> guest ok = yes
> map to guest = Bad User

do you set `guest ok = yes` as a [global] option?
I'm not sure we support it. Only on per-share basis.

-ss

**Comment by sergey-senozhatsky** [comment]
Looking at https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html

>
> guest account (G)
>
>    This is a username which will be used for access to services which are specified as guest ok.
>    ...

So it seems that  `guest ok` is per-service (per-share).
E.g.

> 
> [aprinter]
> 	path = /usr/spool/public
> 	read only = yes
> 	printable = yes
> 	guest ok = yes
>

-ss

**Comment by sergey-senozhatsky** [comment]
>  yet i still need to create a dummy database user even for a guest only setup.

Should be FIXED now (PR).

-ss

**Comment by Andy2244** [comment]
> Should be FIXED now (PR).

Yes i set `guest ok = yes` per share, i assume the default logic was to always check for the database file. On openwrt many users just setup a simple fileshare via guest account, so if this can be done without a database file its one less point of config failure.

**Comment by namjaejeon** [comment]
Pushed Sergey's patches to master!
Thanks for your feedback!

**Comment by Andy2244** [comment]
thanks fixed
