### ISSUE TITLE
[Feature Requests] some interfaces and user related options.

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd-tools#64]
Hi, i would like to see the following or similar parameters to-be implemented.

```
interfaces
bind interfaces only
```
This is because openwrt on router/nas devices can have multiple interfaces (lan, wan, bridges...) and usually you only want the fileserver on the lan/bridge.

```
force group = root
force user = root
inherit owner = windows and unix
```
I would like a option to specify a owner for new files/folders, independent of the cifs login user. That's so multiple user can be given different access, but all files belong to the same base user.

```
deadtime
```
It seems connections are kept open, even after closing from the client side, so having some option to specify the time connections are kept open without any traffic would be nice.

**Comment by namjaejeon** [comment]
Okay, Will check them:)

**Comment by namjaejeon** [comment]
Just information, I add create/directory mask in cifsd. Could you please confirm that it was implemented as you thought? regarding Server Signing, I did not understand exactly what was the problem... Could you elaborate more what is difference with samba..?

**Comment by Andy2244** [comment]
> Server Signing, I did not understand exactly what was the problem... Could you elaborate more what is difference with samba..?

This is more related to sambas `smb encrypt` option, we would like to have the ability to control where and when encryption, signing is used. That's because many embedded devices lack proper hardware encryption support, so cpu usage gets high on software encryption packages like samba/vpn. So having the ability to disable all encryption overhead for a simple LAN fileshare to get better speeds is a valid trade-off, many openwrt users would accept.

PS: From what i understand smb3 still allows for unencrypted/signed modes?

**Comment by namjaejeon** [comment]
Okay, I see. Let me check.

Signing is enable at default in cifsd if negotiation dialect is SMB3. hm... I need to check it is true whether signing should be always enable in SMB3 although server signing is false.
If it is not true, I will change codes not to turn on signing at default with SMB3 client(windows 10).
and regarding encryption, I recently changed it is defautly disable.(https://github.com/namjaejeon/cifsd/commit/cb0935bc2660f178a9ab005ebd92c248a518200e)
maybe, I should add "smb encrypt" parameter to control encryption support.

Yes, it allowed. current cifsd master work on unencrypted/signed modes with windows 10 client(SMB3)

**Comment by Andy2244** [comment]
Yeah having options to control both would be great, some want encryption, signing and have the hardware support for it and some don't. So being able to easily control this would be the most flexible.

**Comment by Andy2244** [comment]
> Just information, I add create/directory mask in cifsd. Could you please confirm that it was implemented as you thought?

Works fine now thanks.

**Comment by namjaejeon** [comment]
@Andy2244 I am adding interfaces parameter support now. the connection restriction of specific device(wlan0 or eth0, etc) is done. Do you want to use IP Address range(IP/mask pair) restriction support in interfaces parameter ?

**Comment by Andy2244** [comment]
> Do you want to use IP Address range(IP/mask pair) restriction support in interfaces parameter ?

Keep it samba compatible please, aka:
```
bind interfaces only = yes
interfaces = lo eth0
```

**Comment by namjaejeon** [comment]
> bind interfaces only = yes
> interfaces = lo br-lan wan

This is well supported in the current patch.

> If you want to add ip range support, i would suggest a new parameter.

I wonder if there is a scenario where IP range is used in openWRT. If not, I want to make low priority.

**Comment by Andy2244** [comment]
From what i have seen, most just want a simple and fast fileshare on there potato 4/32 router, without jumping through too many hoops aka installing smbv1 support in Win10 or fiddling with obscure config files.

So yeah put the ip range on low priority.

**Comment by namjaejeon** [comment]
Okay Thanks for your answer:)

interfaces, bind interfaces only (https://github.com/cifsd-team/cifsd/commit/2e8b6f57f67a654f450d741973802860c90821d7) are ready.
