### ISSUE TITLE
startup error's on missing "[global]" and last LF in smb.cfg

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd-tools#66]
ok i got the same "ERROR: Recv() error No error information" again and i found out why.
If `[global]` is missing or the last line has no LF, than this error happens.

this fails 
```
[share]
	path = /mnt/sda
	valid users = andy
	guest ok = no
```
this works
```
[global]

[share]
	path = /mnt/sda
	valid users = andy
	guest ok = no
```
Similar if you forget a LF in the last line it will also fail.

NOTE: If it did succeeded once, you need to reset (rmmod) the kernel module again to see fails again, otherwise it seems to reuse some internal data. So after each smb.cfg change rmmod/modprobe to ensure proper testing. Thats why i could reproduce the error, when i encountered it the first time.

**Comment by sergey-senozhatsky** [comment]
> If [global] is missing [..] than this error happens

FIXED.

> Similar if you forget a LF in the last line it will also fail.

Will take a look.

Thanks.
-ss

**Comment by sergey-senozhatsky** [comment]
> If [..] the last line has no LF, than this error happens.

Should be FIXED.

-ss

**Comment by Andy2244** [comment]
fixed thanks
