### ISSUE TITLE
"server signing" parameter?

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd-tools#67]
I try to verify this smb 3.1.1 feature: [pre-authentication-integrity](https://blogs.msdn.microsoft.com/openspecification/2015/08/11/smb-3-1-1-pre-authentication-integrity-in-windows-10/)

I did disable server signing on the server via:
`server signing = disabled`

On the Windows 10 client i use `LmCompatibiltyLevel=5` and enabled `EnableSecuritySignature`, `RequireSecuritySignature`.

yet i can connect to the share via:
`net use a: \\router\sharex /user:andy`

```
Get-SmbConnection

ServerName ShareName UserName    Credential Dialect NumOpens
---------- --------- --------    ---------- ------- --------
router     sharex    GAMEPC\andy \andy      3.1.1   1
```

```
Get-SmbClientConfiguration

ConnectionCountPerRssNetworkInterface : 4
DirectoryCacheEntriesMax              : 16
DirectoryCacheEntrySizeMax            : 65536
DirectoryCacheLifetime                : 10
DormantFileLimit                      : 1023
EnableBandwidthThrottling             : True
EnableByteRangeLockingOnReadOnlyFiles : True
EnableInsecureGuestLogons             : True
EnableLargeMtu                        : True
EnableLoadBalanceScaleOut             : True
EnableMultiChannel                    : True
EnableSecuritySignature               : True
ExtendedSessionTimeout                : 1000
FileInfoCacheEntriesMax               : 64
FileInfoCacheLifetime                 : 10
FileNotFoundCacheEntriesMax           : 128
FileNotFoundCacheLifetime             : 5
KeepConn                              : 600
MaxCmds                               : 50
MaximumConnectionCountPerServer       : 32
OplocksDisabled                       : False
RequireSecuritySignature              : True
SessionTimeout                        : 60
UseOpportunisticLocking               : True
WindowSizeThreshold                   : 8
```

My understanding is that this should not be possible in this configuration? Do i miss some option or misunderstand the parameter?

PS: I was trying to test what performance/cpu impact this option has and what defaults to use.

**Comment by Andy2244** [comment]
I just noticed that `create mask, directory mask` while read from the config file is not really used anywhere and do not work.

So i suspect that other parameters like `server signing, oplocks`, might not be implemented as well?
Is there a updated list of parameters that are supposed to work currently?

**Comment by namjaejeon** [comment]
Hi Andy,
First, Thanks for your report!
You can see supported parameter list in cifsd-tools/smb.conf.example. and As you said, cifsd doesn't support for server signing , oplock and create mask, etc. parameters in smb.conf yet. because we implemented ones we needed now first. If you want it, we can support them. and we implemented oplock/lease feature, but it is not stable. So I made forcbily it disable. except oplock, We can probably implement them.
