### ISSUE TITLE
"Access is denied." errors while trying to run binarys from share.

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd-tools#68]
I use F2FS as filesystem on the share and while i can run scriptfiles directly from the share any executable binary refuses to start with "Access is denied.". The files/folders on the share are all set to 0777 access.

Is this a FS problem, since the mapped share actually reports "F2FS" via share/properties on Windows 10, while via samba3/4 it was always reported as NTFS, no matter what the actual FS was.

```
Start.exe
Access is denied.
```
Yet i can edit/open the file via hexeditor just fine, so i have at least read, write access.

So is this a know limitation currently, do i miss some parameter or what can i try to get binarys working directly from the share?

**Comment by Andy2244** [comment]
ok got it to work if i use it with writeable yes and in guest mode, but its slow and buggy throwing those tonns of those lock errors.
```
map to guest = Bad User
writeable = yes
guest ok = yes
```

```
kern.err kernel: [ 1982.779332] kcifsd: smb2_lock:5918: the end offset(ffffffffffffffff) is smaller than the start offset(0)
kern.err kernel: [ 1982.788969] kcifsd: smb2_lock:6164: failed in taking lock(flags : 1)
```

**Comment by namjaejeon** [comment]
oplock is different with smb2 lock. oplock is a lock for cache mechanism. and smb2_lock is byte lock we think normally. so oplock = yes, no. is no useful for this error message. I sent relevant patch to change this error message to debug. will push to master soon.

Thanks for your report!!

**Comment by Andy2244** [comment]
@namjaejeon yeah i understand, i tried oplock just to test if this has a impact on the failing binary's. As example under samba4 i can run [portableapps.com](https://portableapps.com/) directly from the share, while with cifsd it breaks and crashes.

**Comment by namjaejeon** [comment]
I found it is relatd with streamed file open. checking it now, will fix it soon.

**Comment by namjaejeon** [comment]
Andy, Could you please check it with updated master branch to know that it is fixed or not on your side ?

**Comment by namjaejeon** [comment]
hm... it do randomly works well.. need to check more..

**Comment by namjaejeon** [comment]
could you confirm this issue is coming on only windows 10 ?

**Comment by namjaejeon** [comment]
I found when problem is coming. installer(.exe) have worked after win10 client reconnect & cifsd server reboot case. maybe, it is different issue you raise. could you please check it with latest master branch on your side ?

**Comment by Andy2244** [comment]
Just checked getting different errors now:
```
[350364.037698] kcifsd: create_smb2_pipe:1744: Unable to open RPC pipe: -22
[350364.045576] kcifsd: create_smb2_pipe:1744: Unable to open RPC pipe: -22
[350576.447993] kcifsd: cifsd_vfs_create:53: path create failed for /mnt/sda/2/PortableApps/PortableApps.com/Data/PortableAppsMenu.ini, err -2
[350588.383328] kcifsd: create_smb2_pipe:1744: Unable to open RPC pipe: -22
```
using
```
[global]
	server string = CIFSD on OpenWRT
	ipc timeout = 5
	map to guest = Bad User

[share]
	path = /mnt/sda
	writeable = yes
	guest ok = yes
```

I just mounted the share as a network drive in windows 10 and than installed PortableApps.com into the test folder, this worked fine and all folders, files are created with nogroup/nobody. Than if you start the "start.exe" i keep getting the write denied access error for PortableAppsMenu.ini.

**Comment by namjaejeon** [comment]
Got it, I will make default fs type of cifsd as NTFS.

**Comment by namjaejeon** [comment]
Pushed! And I can not run start.ext file, this application is blocked with security alarm in my company.
hm.. don't know why..
Could you please check it with latest cifsd master ?
Thanks!

**Comment by Andy2244** [comment]
@namjaejeon Same problem, getting tonns of those:
```
[449409.981530] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449421.280132] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449421.288102] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449421.298431] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449421.306932] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449421.343809] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449421.352808] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449421.440162] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449421.447773] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449427.442458] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
[449427.450401] kcifsd: create_smb2_pipe:1689: Unable to open RPC pipe: -22
```

I don't see this error anymore, but the app still cant write to its PortableAppsMenu.ini file.
`cifsd_vfs_create:53: path create failed for /mnt/sda/2/PortableApps/PortableApps.com/Data/PortableAppsMenu.ini, err -2`

The mounted filesystem is now reported as NTFS.

**Comment by namjaejeon** [comment]
Okay, I found why write failure happened. Please try current master branch again!
Thanks for your feedback!

**Comment by Andy2244** [comment]
@namjaejeon ok the fix worked for me, i tested firefox portable this way and looks good. Yet i noticed firefox portable complains about this issue:
https://support.mozilla.org/en-US/kb/fix-bookmarks-and-history-will-not-be-functional?redirectlocale=en-US&as=u&redirectslug=The+bookmarks+and+history+system+will+not+be+functional&utm_source=inproduct

It seems it cannot lock `places.sqlite`, i assume this is a separate issues and i should maybe opena new issues for this?

**Comment by namjaejeon** [comment]
Ah, okay, You don't need to open newly. I will check it!

**Comment by namjaejeon** [comment]
FIXED. Please check the latest master.
PS: Install portableapp again after removing all as well as firefox.

**Comment by Andy2244** [comment]
@namjaejeon ok Firefox now works correctly thanks, which should cover most other programs. The only other harder case i know of is running MS-Office from a share, which is really a edge case.

PS: I still got this once after a fresh reinstall of potableapps, not sure maybe that's just the initial probing for the file?
`kern.err kernel: [869378.638707] kcifsd: cifsd_vfs_create:53: path create failed for /mnt/sda/2/PortableApps/PortableApps.com/Data/PortableAppsMenu.ini, err -2`
