### ISSUE TITLE
Assertion failed: 0 (lib/socket.c) ?

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd-tools#79]
Just got this one, which seems new.
```
 cifsd -n
[cifsd-worker/32287]: ERROR: Can't open `/etc/cifs/cifsdpwd.db': No such file or directory
[cifsd-worker/32287]: ERROR: User database file does not exist. Only guest sessions (if permitted) will work.
[cifsd-worker/32287]: ERROR: Unsupported share info level (write): 2
[cifsd-worker/32287]: ERROR: Unsupported share info level (read): 2
[cifsd-worker/32287]: ERROR: SRVSVC: unsupported INVOKE method 21
^C[cifsd-worker/32287]: ERROR: Child received signal: 2 (Interrupt)
[cifsd-worker/32287]: ERROR: Child received signal: 2 (Interrupt)
BUG at file position lib/socket.c:134:release_local_port
Assertion failed: 0 (lib/socket.c: release_local_port: 134)
[cifsd-manager/32286]: INFO: Exiting. Bye!
```

**Comment by sergey-senozhatsky** [comment]
Hmm.

[cifsd-worker/32287]: ERROR: Child received signal: 2 (Interrupt)
[cifsd-worker/32287]: ERROR: Child received signal: 2 (Interrupt)

Two signals. The assertion is from libnl - zero libnl PID:

> 122 static void release_local_port(uint32_t port)                                                                                                                                                                                                                                                                              
> 123 {                                                                               
> 124         int nr;                                                                 
> 125         uint32_t mask;                                                          
> 126                                                                                 
> 127         BUG_ON(port == 0);                                                      
> 128                                                                                 
> 129         nr = port >> 22;                                                        
> 130         mask = 1UL << (nr % 32);                                                
> 131         nr /= 32;                                                               
> 132                                                                                 
> 133         nl_write_lock(&port_map_lock);                                          
> 134         BUG_ON((used_ports_map[nr] & mask) != mask);                            
> 135         used_ports_map[nr] &= ~mask;                                            
> 136         nl_write_unlock(&port_map_lock);                                        
> 137 }        

At the same time nl_sock was not NULL, but _probably_ was partially destoyed

> 243 void nl_socket_free(struct nl_sock *sk)                                         
> 244 {                                                                               
> 245         if (!sk)                                                                
> 246                 return;                                                         
> 247                                                                                 
> 248         if (sk->s_fd >= 0)                                                      
> 249                 close(sk->s_fd);                                                
> 250                                                                                 
> 251         if (!(sk->s_flags & NL_OWN_PORT))                                       
> 252                 release_local_port(sk->s_local.nl_pid);                                                                                                                                                                                                                                                                    
> 253                                                                                 
> 254         nl_cb_put(sk->s_cb);                                                    
> 255         free(sk);                                                               
> 256 }                                                                               
> 

Which makes me think that our sighandler is not entirely re-entrable.
Will take a look.

-ss

**Comment by sergey-senozhatsky** [comment]
RFC patch available, let's see if this can address the issue. OTOH do we really need to perform worker_process_free() there?.. Can just exit() and let the OS release all the memory which we
have allocated; but this will make valgrind report much bigger and harder to read. So let's see
if atomic op will do the trick.

-ss

**Comment by namjaejeon** [comment]
Pused Sergey's patch for this issue.

**Comment by namjaejeon** [comment]
Pushed Sergey's patch for this issue.

**Comment by Andy2244** [comment]
ok don't get the assert anymore:
```
root@router:~# cifsd -n
[cifsd-worker/30868]: ERROR: Can't open `/etc/cifs/cifsdpwd.db': No such file or directory
[cifsd-worker/30868]: ERROR: User database file does not exist. Only guest sessions (if permitted) will work.
[cifsd-worker/30868]: ERROR: Unsupported share info level (write): 2
[cifsd-worker/30868]: ERROR: Unsupported share info level (read): 2
[cifsd-worker/30868]: ERROR: SRVSVC: unsupported INVOKE method 21
[cifsd-worker/30868]: ERROR: Unsupported share info level (write): 2
[cifsd-worker/30868]: ERROR: Unsupported share info level (read): 2
[cifsd-worker/30868]: ERROR: SRVSVC: unsupported INVOKE method 21
^C[cifsd-worker/30868]: ERROR: Child received signal: 2 (Interrupt)
[cifsd-worker/30868]: ERROR: Child received signal: 2 (Interrupt)
[cifsd-manager/30867]: INFO: Exiting. Bye!
```
