### ISSUE TITLE
Just calling "cifsadmin" will create a empty cifsdpwd.db.

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/cifsd-tools#80]
If you just call `cifsadmin` by accident, a empty cifsdpwd.db will be created. The tool should check for valid parameters and avoid creating empty files this way.

**Comment by sergey-senozhatsky** [comment]
Can take a look later. (LowPriority)

-ss

**Comment by sergey-senozhatsky** [comment]
Added a simple user name sanity check. Sent a patch; FIXED.

-ss

**Comment by namjaejeon** [comment]
Applied Sergey's patch now.
Thanks!

**Comment by Andy2244** [comment]
fixed thanks
